name: Build system
on:
  push:
  schedule:
    # 3:20 am every day
    - cron: '20 3 * * *'

defaults:
  run:
    shell: bash
    working-directory: /
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: leemagnusson/ros
    steps:
    - name: build
      run: |
        cd /
        ./repo init -b main -u https://github.com/unhuman-io/freebot-manifest
        ./repo sync
        ./freebot/install_freebot_build_deps.sh
        ./freebot/build_freebot.sh
    - name: test
      run: |
        echo test
        . catkin-ws/devel/setup.bash 
        # help for rospkg and yaml error: https://github.com/stereolabs/zed-ros-wrapper/issues/569
        apt install -y python-is-python3
        roslaunch freebot-ros freebot_hardware.launch & sleep 5 && kill %1
