name: Make jetson image
on:
  push:
    branches:
      - jetson-images
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free up 24GB of disk space
        run: sudo rm -rf /usr/share/dotnet
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./make_jetson_nano.sh
      - name: Upload images
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: jetson_nano/Linux_for_Tegra/tools/*.img
