name: Make jetson image
on:
  push:
    branches:
      - jetson-images
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Free space
        run: |
          echo "Free space:"
          df -h
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./make_jetson_nano.sh
      - name: Upload images
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: jetson_nano/Linux_for_Tegra/tools/*.zip
